language: python
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
#  - "nightly" # Awaiting https://github.com/cython/cython/milestone/74
install:
  - pip install -r requirements_dev.txt
script:
  - pytest --cov=jdict --cov-report=term
after_success:
  - codecov
